os: linux

dist: focal

git:
  depth: 1

language: node_js

node_js:
- node

install:
- npm install -g grunt-cli
- npm install
- npm-check node_modules/poststylus -y

script:
- grunt stylus --verbose
- cat KiraPostStylus.css
