os: linux

dist: focal

git:
  depth: 1

cache: false

language: node_js

node_js:
- node

install:
- rvm install ruby --latest
- gem install travis
- npm install -g grunt-cli
- npm install

script:
- grunt shell --verbose
