git:
  depth: 1

language: node_js

node_js:
- node

install:
- npm install -g grunt-cli prettier

before_script:
- npm install

script:
- prettier --write --loglevel debug KiraArchitecture.html
- grunt prettier --verbose
