git:
  depth: 1

language: node_js

node_js:
- 12

before_install:
- export GRUNT_PYLINT_SKIP_POSTINSTALL=yes

install:
- npm install -g grunt-cli
- pip install --upgrade pip && pip install pipenv==11.10.2 && pipenv install --dev

before_script:
- npm install

script:
- grunt pylint --verbose
