os: linux

dist: focal

git:
  depth: 1

cache: false

language: node_js

# [REQUIRED] Secure GitHub token for the Travis CI configuration:
# http://blog.code4hire.com/2016/06/adding-github-token-to-travis-ci-configuration/
env:
  global:
    secure: QVIMzZgQewWOrweiXZwOpRFMp2Xs6VgDpM7BR50hGIPEA5A5cmstI6gJAhi0M55DPkNWrtTLIKtbNhOvR861wVlZwqg1bxnmuqxhonpMooIV24PTFDo4tDo50UvuwhUqhqHvf0ugXalkA0QEoEaIBZlqXX+tvkvMJHwV7uONAYgxOx7z8tQ9v9yTXq2/Aos9Yt6Wb+37oFJGsLlZX6CLYIUOq5iFem+hkVrIOJrxB3PUch8L/L+pHy3i9NnGm95HBqptwkR+6NBgE/A3ZFFFLs7R28hDcQvtFZqJe1OIdclFutcNSAlElyn/i6y41oIIRnEnote7mZ5q3tzX+Mo6hjXZV2+nzKUc98x4QRWGqj3HghxcFtCSC4SZRt6gI2ayxzglWsaCfNqT6J6R+xBEN08jUwfZAHzXudeENrUzJaWm8iH3LEf4w4rMAoBHg7RO0lIz+LrmVtuBfM4Czkk8nyE+uhxdFDXNNmb6Pup/BwlOxcwjnbM+QU6mpoJyzb/HTUO2azoOx5D5zGDcBQ/J7BWNfbHmbx8hINYKnkylMOufkd/4F54iWStiuegX/vAGfDfBD4cjlGw0M0hAuO7r7ZNinWW0jWH/sD8z/XgXy0pDVH5Hl6tSGvK3rXfd88b5vwTXYv7rw7OwJjLCKlHEfNM0tOKc1f0mxgdatxzLCqE=

node_js:
# [INFO] The latest stable Node.js release:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
- node

install:
# [INFO] The latest stable Ruby version already default for Focal Fossa Build environment
# on the October 2020:
# https://docs.travis-ci.com/user/reference/focal/#ruby-support
- gem install travis
- npm install -g grunt-cli
- npm install

script:
# [INFO] Lint “.travis.yml” file locally:
# https://stackoverflow.com/a/35607499/5951529
# [INFO] “-x” option — exit code 1 if there are any warnings:
# https://www.rubydoc.info/gems/travis/1.10.0#lint
- travis lint -x
- grunt shell --verbose
