git:
  depth: 1
dist: xenial
language: python
node_js:
- 11
python: 3.7
install:
- npm install -g grunt-cli
- pip install pipenv==11.10.2 && pipenv install --dev
before_script:
- npm install
script:
- grunt pylint --verbose
