os: linux

dist: focal

git:
  depth: 1

cache: false

language: node_js

node_js:
- node

install:
- npm i -g grunt-cli purgecss
- npm i

script:
- purgecss --css KiraGoddess.css --content KiraGoddess.html
- grunt purgecss --verbose --stack
- cat KiraGoddess.css
