os: linux

dist: focal

git:
  depth: 1

cache: false

language: node_js

node_js:
- node

install:
- npm install -g grunt-cli posthtml posthtml-img-autosize
- npm install

script:
- grunt posthtml --verbose
- posthtml KiraPostHTML.html -o KiraImgAutosizeCLI.html -u posthtml-img-autosize --posthtml-img-autosize.processEmptySize true
- cat KiraImgAutosizeCLI.html
- cat KiraImgAutosizeGrunt.html
