os:
- linux
- osx
- windows

dist: focal

osx_image: xcode12.2

git:
  depth: 1

cache: false

language: node_js

node_js:
- node

install:
- npm i -g grunt-cli google-closure-compiler
- npm i

script:
- grunt closure-compiler --verbose --stack
- google-closure-compiler --js KiraChocolat.js --language_out ECMASCRIPT_NEXT --warning_level VERBOSE --jscomp_warning "*" --jscomp_off undefinedVars
- google-closure-compiler --js KiraChocolat.js --language_out ECMASCRIPT_NEXT --warning_level VERBOSE --jscomp_warning "*"
