git:
  depth: 1
language: node_js
node_js:
- 11
install:
- npm install -g grunt-cli purgecss
before_script:
- npm install
matrix:
  include:
  - script:
    - grunt purgecss
  - script:
    - "purgecss --css KiraGoddess.css --con KiraGoddess.html --out . --whitelist KiraSecond"
after_success:
- cat KiraGoddess.css
