platform: x64

image: Visual Studio 2019

clone_depth: 1

install:
- choco install nodejs -y
- npm install -g grunt-cli posthtml-cli posthtml-img-autosize
- npm install

build_script:
- echo Kira Goddess!

test_script:
- posthtml KiraPostHTML.html -o KiraImgAutosizeCLI.html -u posthtml-img-autosize --posthtml-img-autosize.processEmptySize true

on_failure:
- grunt posthtml --verbose
