platform: x64

init:
- SETX GRUNT_PYLINT_SKIP_POSTINSTALL yes

environment:
  nodejs_version: "12"
  PYTHON: C:\Python37-x64

install:
- npm install -g grunt-cli
- "%PYTHON%\\python -m pip install --upgrade pip & pip3 install pipenv==11.10.2 & pipenv install --dev"

before_build:
- npm install

build_script:
- grunt pylint --verbose
