environment:
  nodejs_version: "11"
  PYTHON: C:\Python37-x64

install:
- npm install -g grunt-cli
- pip install pipenv==11.10.2 && pipenv install --dev

before_build:
- npm install

build_script:
- grunt pylint --verbose
