platform: x64

image: Visual Studio 2019

clone_depth: 1

install:
- choco install nodejs -y
- npm install -g grunt-cli posthtml-cli posthtml-img-autosize
- npm install

test_script:
- posthtml KiraPostHTML.html -o KiraImgAutosizeCLI.html -u posthtml-img-autosize --posthtml-img-autosize.processEmptySize true
- grunt posthtml --verbose
- cat KiraImgAutosizeCLI.html
- cat KiraImgAutosizeGrunt.html
